name: Update CPC Cases

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Update dataset
        run: python scripts/update_cases.py
      - name: Commit changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add data/raw_cases data/sdbench/cases data/sdbench/hidden_cases
          if git diff --cached --quiet; then
            echo "No updates" && exit 0
          fi
          git commit -m 'chore: update CPC cases'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
